//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GosAutoInspection.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int ID { get; set; }
        public int DriverID { get; set; }
        public int LicenceID { get; set; }
        public string VIN { get; set; }
        public int ManufacturerID { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Color { get; set; }
        public int EngineType { get; set; }
        public int TypeOfDriveID { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual Licences Licences { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual TypesOfDrive TypesOfDrive { get; set; }
    }
}
