//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GosAutoInspection.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licences
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Licences()
        {
            this.Cars = new HashSet<Cars>();
        }
    
        public int ID { get; set; }
        public int DriverID { get; set; }
        public Nullable<System.DateTime> LicenceDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public int CategoryID { get; set; }
        public string LicenceSeries { get; set; }
        public string LicenceNumber { get; set; }
        public int StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cars> Cars { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
